### PR TITLE
Enable finalizer elision for HashMap backing

### PR DESCRIPTION
**Pull request by jacob-hughes**
I'm not sure what the best way to raise this is. Our version of hashbrown is v0.14.5, which is a bit behind master at this point. We can't merge my changes into master unless we rebased Alloy with rustc so they'll have to be a separate branch for now. I'm raising a draft PR so that you can still have eyes on this, but if you have another suggestion I'm open to it?

### CODE REVIEW

**Comment by ltratt** [comment]
For the time being, keeping this draft PR opening and pushing to it seems tolerable. We can do something more clever later if needed.

**Comment by jacob-hughes** [comment]
Ok :+1:

**Comment by jacob-hughes** [comment]
Hmm, that file doesn't seem to be being picked up by rustfmt for some reason. Fixed it here 5f94fdafb3d6d1824171d728e330e41f4fb5d8da

**Comment by jacob-hughes** [comment]
Closing in order to raise directly on softdev branch.

**Pull request closed without merging**
